#!/bin/bash

setup_config() {
    local SCENEWEAVER_DIR="$1"
    local WORKSPACE_DIR="$2"

    print_header "Setting Up Configuration Files"

    cd "${SCENEWEAVER_DIR}"

    # 1. Create key.txt template
    if [ ! -f "Pipeline/key.txt" ]; then
        cat > "Pipeline/key.txt.template" << 'EOF'
# Add your Azure OpenAI API key here
# Replace this file with Pipeline/key.txt containing your actual key
your-azure-openai-api-key-here
EOF
        cp "Pipeline/key.txt.template" "Pipeline/key.txt"
        print_success "Created Pipeline/key.txt template"
        print_warning "Remember to add your actual API key to Pipeline/key.txt"
    else
        print_warning "Pipeline/key.txt already exists, not overwriting"
    fi

    # 2. Create config.json template if needed
    if [ ! -f "Pipeline/config/config.json" ]; then
        cat > "Pipeline/config/config.json" << 'EOF'
{
    "llm_name": "gpt-4.1-2025-04-14",
    "llm_config": {
        "base_url": "YOUR_AZURE_ENDPOINT/openai/deployments/YOUR_DEPLOYMENT_ID",
        "api_version": "2025-03-01-preview"
    }
}
EOF
        print_success "Created Pipeline/config/config.json template"
        print_warning "Remember to update Azure endpoint and deployment ID"
    else
        print_info "Pipeline/config/config.json already exists"
    fi

    # 3. Create .env file for path configuration
    cat > "${SCENEWEAVER_DIR}/.env" << EOF
# SceneWeaver Environment Configuration
# Auto-generated by setup script

# Workspace directory (where external tools and datasets are stored)
WORKSPACE_DIR=${WORKSPACE_DIR}

# External tool paths
SD35_DIR=${WORKSPACE_DIR}/sd3.5
ACDC_DIR=${WORKSPACE_DIR}/Tabletop-Digital-Cousins
IDESIGN_DIR=${WORKSPACE_DIR}/IDesign
HOLODECK_DIR=${WORKSPACE_DIR}/Holodeck

# Dataset paths
FUTURE_3D_DIR=${WORKSPACE_DIR}/datasets/3D-FUTURE
METASCENES_DIR=${WORKSPACE_DIR}/datasets/metascenes
PHYSCENE_DIR=${SCENEWEAVER_DIR}/data/physcene

# Output directory
OUTPUT_DIR=${SCENEWEAVER_DIR}/output

# Objaverse cache
OBJAVERSE_CACHE=${HOME}/.objaverse
EOF
    print_success "Created .env configuration file"

    # 4. Update paths in GPT/constants.py
    if [ -f "GPT/constants.py" ]; then
        print_info "Updating Holodeck path in GPT/constants.py..."
        # Backup original
        cp "GPT/constants.py" "GPT/constants.py.bak"

        # Update ABS_PATH_OF_HOLODECK
        sed -i "s|ABS_PATH_OF_HOLODECK = .*|ABS_PATH_OF_HOLODECK = '${WORKSPACE_DIR}/Holodeck/'|" "GPT/constants.py"
        print_success "Updated GPT/constants.py"
    fi

    # 5. Create .gitignore entries
    print_info "Updating .gitignore..."

    # Check if entries already exist
    if ! grep -q "Pipeline/key.txt" "${SCENEWEAVER_DIR}/.gitignore" 2>/dev/null; then
        cat >> "${SCENEWEAVER_DIR}/.gitignore" << 'EOF'

# Sensitive configuration files
Pipeline/key.txt
.env

# Downloaded datasets
datasets/

# Blender installation
blender/

# Python environments
.venv/

# Output files
output/
EOF
        print_success "Updated .gitignore"
    else
        print_info ".gitignore already contains SceneWeaver entries"
    fi

    print_success "Configuration setup complete"
}
